on:
  push:
    branches: main
  
name: Render

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3    
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        # To install LaTeX to build PDF book 
        tinytex: true 
        # uncomment below and fill to pin a version
        # version: SPECIFIC-QUARTO-VERSION-HERE
    - name: Setup Julia
      uses: julia-actions/setup-julia@latest
      with:
        version: 1.9
    - name: Julia Cache
      uses: julia-actions/cache@v1
    - name: Cache Quarto
      id: cache-quarto
      uses: actions/cache@v3
      env:
        cache-name: cache-quarto
      with:
        path: _freeze
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('*.qmd') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@v2